baseURL = "https://cifer97.github.io"
languageCode = "zh-CN"
title = "编程笔记"
theme = "yinyang"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Cifer"
  homepage = "https://cifer76.github.io/"

#[languages]
#  [languages.en]
#    contentDir = "content/en"
#    languageName = "English"
#    weight = 2
#  [languages.cn]
#    contentDir = "content/cn"
#    languageName = "Chinese"
#    weight = 1

[params]
headTitle = "编程笔记"
mainSections = ["posts"]
disqus = "justforfree" # disqus account name

[[params.socials]]
name = "Books"
link = "/reading"
[[params.socials]]
name = "How to learn new things"
link = "/how-to-learn"
[[params.socials]]
name = "Investing"
link = "/investingrule"
[[params.socials]]
name = "Skills"
link = "/eight-part-essay"
[[params.socials]]
name = "Github"
link = "https://github.com/cifer76"
